//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace borsa.Models.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item()
        {
            this.KullaniciItem = new HashSet<KullaniciItem>();
        }
    
        public int ItemId { get; set; }
        public string ItemAdi { get; set; }
        public Nullable<int> ItemMiktari { get; set; }
        public Nullable<decimal> Fiyat { get; set; }
        public Nullable<int> KullaniciId { get; set; }
        public Nullable<bool> ItemOnay { get; set; }
    
        public virtual Kullanicilar Kullanicilar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KullaniciItem> KullaniciItem { get; set; }
    }
}
