//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace borsa.Models.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class KullaniciItem
    {
        public int KullaniciItemId { get; set; }
        public Nullable<int> KullaniciId { get; set; }
        public Nullable<int> ItemId { get; set; }
        public Nullable<decimal> ItemMiktari { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Kullanicilar Kullanicilar { get; set; }
    }
}
